---

name: 'Handlebars'
author: 'felddy'
branding:
  icon: 'edit'
  color: 'purple'
description: 'Apply a handlebars template'
inputs:
  template:
    required: true
    description: 'Template filename'
  json:
    required: true
    description: 'JSON input object'
  dest:
    required: false
    description: 'Output filename'
outputs:
  result:
    description: 'Rendered template'

runs:
  using: 'node16'
  main: 'dist/index.js'
