---

name: 'Render Handlebars template'
author: 'felddy'
branding:
  icon: 'edit'
  color: 'purple'
description: 'Apply a handlebars template'
inputs:
  template_file:
    required: false
    description: 'Handlebars template filename'
  input_file:
    required: false
    description: 'JSON input object'
  template:
    required: false
    description: 'Handlebars template'
  input:
    required: false
    description: 'Handlebars template input'
  output_file:
    required: false
    description: 'Output filename for rendered template'
outputs:
  result:
    description: 'Rendered template data'

runs:
  using: 'node16'
  main: 'dist/index.js'
