---

name: Render README

on:
  push:
    paths:
      - __tests__/test_data.json
      - README.md.hbs

jobs:
  readme-handlebars:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@18bf8ad2ca49c14cbb28b91346d626ccfb00c518
        with:
          egress-policy: audit  # TODO: change to 'egress-policy: block' after couple of runs
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@516dbb0c760f39b4cdd750ae095f1688780f68f4
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        # Store file contents in environment variable
      - name: Read input object file
        id: fam
        run: |
          echo 'TEST_DATA<<EOF' >> $GITHUB_ENV
          cat __tests__/test_data.json >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Run handlebars action
        uses: ./
        with:
          template_file: README.md.hbs
          input: |
            {
              "github": ${{ toJson(github) }},
              "fam": ${{ env.TEST_DATA }}
            }
          output_file: README.md
      - uses: stefanzweifel/git-auto-commit-action@49620cd3ed21ee620a48530e81dba0d139c9cb80
        with:
          commit_message: "Update generated README"
