---

name: 'build-test'
on:  # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - develop
      - 'releases/*'

jobs:
  build:  # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@dd2c410b088af7c0dc8046f3ac9a8f4148492a95
        with:
          egress-policy: audit  # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - run: |
          npm install
      - run: |
          npm run all
  test:  # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@dd2c410b088af7c0dc8046f3ac9a8f4148492a95
        with:
          egress-policy: audit  # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - uses: ./
        with:
          template_file: ./__tests__/template.md.hbs
          input_file: ./__tests__/test_data.json
